# Generated by Django 4.2.4 on 2024-07-22 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("timelines", "0002_rename_timeline_area_event_event_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScientificTimeline",
            fields=[
                (
                    "timeline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timelines.timeline",
                    ),
                ),
                (
                    "scale_unit",
                    models.IntegerField(
                        choices=[
                            (100, "0.1 Thousand Years"),
                            (500, "0.5 Thousand Years"),
                            (1000, "1.0 Thousand Years"),
                            (100000, "0.1 Million Years"),
                            (500000, "0.5 Million Years"),
                            (1000000, "1.0 Million Years"),
                            (100000000, "0.1 Billion Years"),
                            (500000000, "0.5 Billion Years"),
                            (1000000000, "1.0 Billion Years"),
                        ],
                        default=10,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
            bases=("timelines.timeline",),
        ),
        migrations.CreateModel(
            name="ScientificEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timelines.event",
                    ),
                ),
                ("start_year_fraction", models.FloatField(default=1.0)),
                (
                    "start_multiplier",
                    models.IntegerField(
                        choices=[
                            (1000, "Thousand years"),
                            (1000000, "Million years"),
                            (1000000000, "Billion years"),
                        ],
                        default=1000,
                    ),
                ),
                ("end_year_fraction", models.FloatField(default=1.0)),
                (
                    "end_multiplier",
                    models.IntegerField(
                        choices=[
                            (1000, "Thousand years"),
                            (1000000, "Million years"),
                            (1000000000, "Billion years"),
                        ],
                        default=1000,
                    ),
                ),
                (
                    "scientific_timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scientific_timelines.scientifictimeline",
                    ),
                ),
            ],
            options={
                "ordering": ["start_multiplier", "start_year_fraction"],
            },
            bases=("timelines.event",),
        ),
    ]
