# Generated by Django 4.2.4 on 2024-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scientific_timelines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scientifictimeline",
            name="scale_unit",
            field=models.IntegerField(
                choices=[
                    (100, "0.1 Thousand Years"),
                    (500, "0.5 Thousand Years"),
                    (1000, "1.0 Thousand Years"),
                    (100000, "0.1 Million Years"),
                    (500000, "0.5 Million Years"),
                    (1000000, "1.0 Million Years"),
                    (100000000, "0.1 Billion Years"),
                    (500000000, "0.5 Billion Years"),
                    (1000000000, "1.0 Billion Years"),
                ],
                default=1000,
            ),
        ),
    ]
