# Generated by Django 4.2.3 on 2023-08-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelinearea',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='timelinearea',
            unique_together={('timeline', 'page_position')},
        ),
    ]
