# Generated by Django 4.2.3 on 2023-08-06 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0002_alter_timelinearea_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
