# Generated by Django 4.2.3 on 2023-08-06 13:12

from django.db import migrations, models
import timelines.models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, validators=[timelines.models.validate_present]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25, validators=[timelines.models.validate_present]),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(max_length=100, validators=[timelines.models.validate_present]),
        ),
        migrations.AlterField(
            model_name='timelinearea',
            name='name',
            field=models.CharField(max_length=25, validators=[timelines.models.validate_present]),
        ),
    ]
