# Generated by Django 4.2.4 on 2024-03-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("timelines", "0002_rename_timeline_area_event_event_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateTimeTimeline",
            fields=[
                (
                    "timeline_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timelines.timeline",
                    ),
                ),
                (
                    "scale_unit",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Second"),
                            (5, "5 Seconds"),
                            (10, "10 Seconds"),
                            (15, "15 Seconds"),
                            (30, "30 Seconds"),
                            (60, "1 Minute"),
                            (300, "5 Minutes"),
                            (600, "10 Minutes"),
                            (900, "15 Minutes"),
                            (1800, "30 Minutes"),
                            (3600, "1 Hour"),
                            (10800, "3 Hours"),
                            (21600, "6 Hours"),
                            (43200, "12 Hours"),
                            (86400, "1 Day"),
                            (604800, "1 Week"),
                            (101, "1 Month"),
                            (102, "3 Months"),
                            (103, "6 Months"),
                            (104, "1 Year"),
                            (105, "5 Years"),
                            (106, "10 Years"),
                            (107, "100 Years"),
                            (108, "1000 Years"),
                        ],
                        default=86400,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
            bases=("timelines.timeline",),
        ),
        migrations.CreateModel(
            name="DateTimeEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="timelines.event",
                    ),
                ),
                ("start_date_time", models.DateTimeField()),
                ("end_date_time", models.DateTimeField()),
                (
                    "date_time_timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="date_time_timelines.datetimetimeline",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date_time"],
            },
            bases=("timelines.event",),
        ),
    ]
