# Generated by Django 4.2.4 on 2024-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("date_time_timelines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datetimetimeline",
            name="scale_unit",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Second"),
                    (5, "5 Seconds"),
                    (10, "10 Seconds"),
                    (15, "15 Seconds"),
                    (30, "30 Seconds"),
                    (60, "1 Minute"),
                    (300, "5 Minutes"),
                    (600, "10 Minutes"),
                    (900, "15 Minutes"),
                    (1800, "30 Minutes"),
                    (3600, "1 Hour"),
                    (10800, "3 Hours"),
                    (21600, "6 Hours"),
                    (43200, "12 Hours"),
                    (86400, "1 Day"),
                    (401, "1 Week"),
                    (501, "1 Month"),
                    (502, "2 Months"),
                    (503, "3 Months"),
                    (506, "6 Months"),
                    (60001, "1 Year"),
                    (60005, "5 Years"),
                    (60010, "10 Years"),
                    (60100, "100 Years"),
                    (61000, "1000 Years"),
                ],
                default=86400,
            ),
        ),
    ]
