# Generated by Django 4.2.4 on 2024-04-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("date_time_timelines", "0002_alter_datetimetimeline_scale_unit"),
    ]

    choices = [
        (0, "2000-04-03 13:30:15 (year-month-day hour:min:sec)"),
        (1, "2000-04-03 13:30 (year-month-day hour:min)"),
        (2, "2000-04-03 (year-month-day)"),
        (3, "2000-04 (year-month)"),
        (4, "2000 (year)"),
        (5, "04-03 13:30:15 (month-day hour:min:sec)"),
        (6, "04-03 13:30 (month-day hour:min)"),
        (7, "04-03 (month-day)"),
        (8, "04 (month)"),
        (9, "03 13:30:15 (day hour:min:sec)"),
        (10, "03 13:30 (day hour:min)"),
        (11, "03 (day)"),
        (12, "13:30:15(hour:min:sec)"),
        (13, "13:30 (hour:min)"),
        (14, "13 (hour)"),
        (15, "30:15 (min:sec)"),
        (16, "30 (min)"),
        (17, "15 (sec)"),
        (
            18,
            "Mon 03 Apr 2000 13:30:15 (day day:month:year hour:min:sec)",
        ),
        (
            19,
            "Mon 03 Apr 2000 13:30 (day day:month:year hour:min)",
        ),
        (20, "Mon 03 Apr 2000 (day day:month:year)"),
        (21, "Mon 03 Apr (day day:month)"),
        (22, "Mon 03 (day day)"),
        (23, "Mon (day)"),
        (24, "03 Apr 2000 13:30:15 (day:month:year hour:min:sec)"),
        (25, "03 Apr 2000 13:30 (day:month:year hour:min)"),
        (26, "03 Apr 2000 (day:month:year)"),
        (27, "03 Apr (day:month"),
        (28, "Apr 2000 (month:year"),
        (29, "Apr (month"),
    ]

    operations = [
        migrations.AddField(
            model_name="datetimetimeline",
            name="event_display_format",
            field=models.PositiveSmallIntegerField(
                choices=choices,
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="datetimetimeline",
            name="scale_display_format",
            field=models.PositiveSmallIntegerField(
                choices=choices,
                default=0,
            ),
        ),
    ]
