# Generated by Django 4.2.4 on 2024-05-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "date_time_timelines",
            "0003_datetimetimeline_event_display_format_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="datetimeevent",
            name="end_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="datetimeevent",
            name="start_date_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
