# Generated by Django 4.2.4 on 2024-05-21 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "date_time_timelines",
            "0004_alter_datetimeevent_end_date_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="datetimeevent",
            name="end_date_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="datetimeevent",
            name="start_date_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
