[tool.black]
line-length = 79
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | accounts/migrations
    | age_timelines/migrations
    | timelines/migrations
    | manage.py
    | tplot_site/settings.py
    | tplot_site/wsgi.py
    | tplot_site/asgi.py
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''

[tool.bandit]
exclude_dirs = ["accounts/tests", "age_timelines/tests", "timelines/tests"]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.1.1"
update_changelog_on_bump = true
major_version_zero = true
