# Generated by Django 4.2.3 on 2023-08-09 08:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeTimeline',
            fields=[
                ('timeline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timelines.timeline')),
                ('scale_unit', models.PositiveSmallIntegerField(choices=[(1, '1 Year'), (5, '5 Years'), (10, '10 Years'), (20, '20 Years'), (25, '25 Years'), (50, '50 Years'), (100, '100 Years')], default=10)),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('timelines.timeline',),
        ),
        migrations.CreateModel(
            name='AgeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timelines.event')),
                ('start_year', models.SmallIntegerField(default=0)),
                ('start_month', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(-11)])),
                ('end_year', models.SmallIntegerField(default=0)),
                ('end_month', models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(-11)])),
                ('age_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='age_timelines.agetimeline')),
            ],
            options={
                'ordering': ['start_year', 'start_month'],
            },
            bases=('timelines.event',),
        ),
    ]
