# Generated by Django 4.2.3 on 2023-08-09 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('scale_unit_length', models.PositiveSmallIntegerField(choices=[(1, '1cm'), (2, '2cm'), (3, '3cm'), (4, '4cm'), (5, '5cm'), (6, '6cm'), (7, '7cm'), (8, '8cm'), (9, '9cm'), (10, '10cm'), (12, '12cm'), (15, '15cm'), (20, '20cm'), (25, '25cm'), (30, '30cm')], default=5)),
                ('page_size', models.CharField(choices=[('3', 'A3'), ('4', 'A4'), ('5', 'A5')], default='4', max_length=1)),
                ('page_orientation', models.CharField(choices=[('L', 'Landscape'), ('P', 'Portrait')], default='L', max_length=1)),
                ('page_scale_position', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.timeline')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('page_position', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.timeline')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('timeline', 'page_position')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('has_end', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='timelines.tag')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelines.timeline')),
                ('timeline_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timelines.eventarea')),
            ],
        ),
    ]
