# Generated by Django 4.2.4 on 2024-03-19 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="timeline_area",
            new_name="event_area",
        ),
    ]
