# Generated by Django 4.2.4 on 2024-08-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0002_rename_timeline_area_event_event_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="tag",
            name="display",
            field=models.BooleanField(default=True),
        ),
    ]
