
# Generated by Django 4.2.16 on 2024-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0005_collaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_image",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_tags",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_time",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_to_scale_line",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="scale_length",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (4, "4cm"),
                    (5, "5cm"),
                    (6, "6cm"),
                    (7, "7cm"),
                    (8, "8cm"),
                    (9, "9cm"),
                    (10, "10cm"),
                    (12, "12cm"),
                    (15, "15cm"),
                    (20, "20cm"),
                    (25, "25cm"),
                    (30, "30cm"),
                ],
                default=5,
            ),
        ),
    ]
