# Generated by Django 4.2.16 on 2024-12-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0005_collaborator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeline",
            name="scale_unit_length",
        ),
        migrations.AddField(
            model_name="timeline",
            name="scale_unit_length",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (4, "4cm"),
                    (5, "5cm"),
                    (6, "6cm"),
                    (7, "7cm"),
                    (8, "8cm"),
                    (9, "9cm"),
                    (10, "10cm"),
                    (12, "12cm"),
                    (15, "15cm"),
                    (20, "20cm"),
                    (25, "25cm"),
                    (30, "30cm"),
                ],
                default=5,
            ),
        ),
    ]
