# Generated by Django 4.2.16 on 2024-12-16 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0006_remove_timeline_scale_length_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeline",
            old_name="pdf_page_size",
            new_name="pdf_page_size",
        ),
    ]
