# Generated by Django 4.2.16 on 2024-12-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0007_rename_page_size_timeline_pdf_page_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventarea",
            name="display_event_description",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_image",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_tags",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_time",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventarea",
            name="display_event_to_scale_line",
            field=models.BooleanField(default=True),
        ),
    ]
