# Generated by Django 4.2.16 on 2024-12-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0008_eventarea_display_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
