# Generated by Django 4.2.16 on 2024-12-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timelines", "0009_event_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
