name: Python CICD pipeline

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit Tests
      working-directory: ./tplot_site
      run: coverage run manage.py test

    - name: Coverage Check
      working-directory: ./tplot_site
      run: tplot_site/coverage report --fail-under=80
