name: Python CICD pipeline

env:
  GITHUB_WORKFLOW: ${{ true }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  PASSWORD: ${{ secrets.PASSWORD }}

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.3

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
        pip install flake8
        pip install bandit

    - name: Unit Tests
      run: coverage run manage.py test

    - name: Coverage Check
      run: coverage report --fail-under=80

    - name: Coverage Report
      run: coverage html

    - name: Create coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: ./reports/htmlcov/

    - name: Flake8
      run: flake8 .

    - name: Bandit
      run: bandit -c pyproject.toml -r accounts/ age_timelines/ timelines/ tplot_site/ -f html -o bandit.html

    - name: Create bandit report artifact
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: ./reports/bandit.html
